### ISSUE TITLE
Pretty checkboxes are not aligned vertically with label

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-uikit#123]
![image](https://cloud.githubusercontent.com/assets/281070/11199986/4e5fa39a-8ca0-11e5-8e4f-849a3f0726f1.png)

suggestion:

``` less
.checkbox label {
  &:before {
    top: 3px
  }

  &:after {
    top: 3px;
  }
}

```
