### ISSUE TITLE
Add styles for input file types

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-uikit#59]

**Comment by robmcguinness** [comment]
http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/

```css
.btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}
```
